version: '3.8'
services:
  fx-transactions-database:
    image: postgres:14.1-alpine
    restart: always
    container_name: fx-transactions-database
    environment:
      POSTGRES_USER: "fx_transaction_admin"
      POSTGRES_DB: "fx_transactions"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5438:5432"
    volumes:
      - "fx-transactions-database:/var/lib/postgresql/data"

  fx-transactions-test-database:
    image: postgres:14.1-alpine
    restart: always
    container_name: fx-transactions-test-database
    environment:
      POSTGRES_USER: "fx_transaction_admin"
      POSTGRES_DB: "fx_transactions_test"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5439:5432"
    volumes:
      - "fx-transactions-test-database:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6382:6379"

  fx-transactions-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    container_name: fx-transactions-service
    depends_on:
      - fx-transactions-database
      - fx-transactions-test-database
      - redis
    environment:
      FX_TRANSACTION_DATABASE: "fx_transactions"
      FX_TRANSACTION_DATABASE_USER: "fx_transaction_admin"
      FX_TRANSACTION_DATABASE_PASSWORD: "password"
      FX_TRANSACTION_DATABASE_HOST: "fx-transactions-database"
      FX_TRANSACTION_TEST_DATABASE: "fx_transactions_test"
      FX_TRANSACTION_TEST_DATABASE_USER: "fx_transaction_admin"
      FX_TRANSACTION_TEST_DATABASE_PASSWORD: "password"
      FX_TRANSACTION_TEST_DATABASE_HOST: "fx-transactions-test-database"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - .:/app

volumes:
  fx-transactions-database:
  fx-transactions-test-database: