version: '3.8'
services:
  fx-transactions-database:
    image: postgres:14.1-alpine
    restart: always
    container_name: fx-transactions-database
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5438:5432"
    volumes:
      - "fx-transactions-database:/var/lib/postgresql/data"

  fx-transactions-test-database:
    image: postgres:14.1-alpine
    restart: always
    container_name: fx-transactions-test-database
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5439:5432"
    volumes:
      - "fx-transactions-test-database:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6382:6379"

  fx-transactions-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: fx-transactions-service
    depends_on:
      - fx-transactions-database
      - fx-transactions-test-database
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@fx-transactions-database:5432/postgres
      - TEST_DATABASE_URL=postgres://postgres:password@fx-transactions-test-database:5432/postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=development
    volumes:
      - .:/app

volumes:
  fx-transactions-database:
  fx-transactions-test-database: